### ISSUE TITLE
how to run FWI

### ISSUE THREAD

**Issue by yao050130** [daniel-koehn/SAVA#4]
Hi, I only found the forwarding part in the Code, what should I do for FWI?

**Comment by daniel-koehn** [comment]
Hi @yao050130, unfortunately the SAVA code was developed as part of an industry project. Therefore, the OpenSource SAVA version currently only consists of the forward modelling modules. If our next project proposal will be accepted, I will add a new, revised OpenSource version of the SAVA FWI module - best regards Daniel

**Comment by yao050130** [comment]
Okay, thank you for your reply！
Best wishes



---Original---
From: "Daniel ***@***.***&gt;
Date: Wed, Oct 18, 2023 21:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [daniel-koehn/SAVA] how to run FWI (Issue #4)




 
Closed #4 as completed.
